export const productsActions = {
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  LOAD_PRODUCTS_SUCCESS: "LOAD_PRODUCTS_SUCCESS",
  LOAD_PRODUCTS_ERROR: "LOAD_PRODUCTS_ERROR",

  LOAD_SAVE_PRODUCTS: "LOAD_SAVE_PRODUCTS",
  LOAD_SAVE_PRODUCTS_SUCCESS: "LOAD_SAVE_PRODUCTS_SUCCESS",
  LOAD_SAVE_PRODUCTS_ERROR: "LOAD_SAVE_PRODUCTS_ERROR",

  DELETE_PRODUCT: "DELETE_PRODUCT",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_ERROR: "DELETE_PRODUCT_ERROR",

  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  ADD_PRODUCT_TO_CART_SUCCESS: "ADD_PRODUCT_TO_CART_SUCCESS",
  ADD_PRODUCT_TO_CART_ERROR: "ADD_PRODUCT_TO_CART_ERROR",
};
