export const productsActions = {
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  LOAD_PRODUCTS_SUCCESS: "LOAD_PRODUCTS_SUCCESS",
  LOAD_PRODUCTS_ERROR: "LOAD_PRODUCTS_ERROR",
  LOAD_SAVE_PRODUCTS: "LOAD_SAVE_PRODUCTS",
  LOAD_SAVE_PRODUCTS_SUCCESS: "LOAD_SAVE_PRODUCTS_SUCCESS",
  LOAD_SAVE_PRODUCTS_ERROR: "LOAD_SAVE_PRODUCTS_ERROR",
};
