export const productsActions = {
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  LOAD_PRODUCTS_SUCCESS: "LOAD_PRODUCTS_SUCCESS",
  LOAD_PRODUCTS_ERROR: "LOAD_PRODUCTS_ERROR",

  GET_PRODUCT: "GET_PRODUCT",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_ERROR: "GET_PRODUCT_ERROR",

  LOAD_SAVE_PRODUCTS: "LOAD_SAVE_PRODUCTS",
  LOAD_SAVE_PRODUCTS_SUCCESS: "LOAD_SAVE_PRODUCTS_SUCCESS",
  LOAD_SAVE_PRODUCTS_ERROR: "LOAD_SAVE_PRODUCTS_ERROR",

  DELETE_PRODUCT: "DELETE_PRODUCT",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_ERROR: "DELETE_PRODUCT_ERROR",

  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_ERROR: "UPDATE_PRODUCT_ERROR",
};
